const productosData=[
    {
        nombre:"item1",
        precio:"11",
        id:1
    },
    {
        nombre:"item2",
        precio:"12",
        id:2
    },
    {
        nombre:"item3",
        precio:"13",
        id:3
    },
    {
        nombre:"item4",
        precio:"14",
        id:4
    },
    {
        nombre:"item5",
        precio:"15",
        id:5
    },
    {
        nombre:"item6",
        precio:"16",
        id:6
    },
    {
        nombre:"item7",
        precio:"17",
        id:7
    },
    {
        nombre:"item8",
        precio:"18",
        id:8
    },
]
const containerPrdocuts=document.querySelector(".container-produts");
    productosData.forEach((element)=>{
        
        let productoDom=document.createElement("div");
        productoDom.innerHTML="<p>${element}</p>+<p>precio</p>+<p>id</p>"
        containerPrdocuts.appendChild(productoDom);
        console.log(element);
    })
